### ISSUE TITLE
Use with open-uri-cached

### ISSUE THREAD

**Issue by kntmrkm** [janko-m/down#8] opened 2016-08-07 14:16 UTC
Can I use this gem with `open-uri-cached`?

https://github.com/tigris/open-uri-cached

I tried. but got a below error.

`ActionView::Template::Error (undefined method `metas' for #<StringIO:0x007fead305a968>`

This is my code.

```
# works.
image = open(item.first_image_url)

# this code works first time, but got above error second time.     
#image = Down.download(item.first_image_url, read_timeout: 1)
```

I'm using this gem with Rails project.
thanks.

http://g.recordit.co/2d7a2YEMYs.gif

**Comment by janko-m** [comment] 2016-08-07 14:56
When `open-uri-cached` gem is retrieving the file from the cache, it instantiates a `StringIO` object and [defines some additional methods](https://github.com/tigris/open-uri-cached/blob/master/lib/open-uri/cached.rb#L44-L71) in order to conform [open-uri's additional methods](https://github.com/ruby/ruby/blob/df0e70b90a3198295b5640b36c57ef1266a7a258/lib/open-uri.rb#L413).

The problem is that open-uri-cached isn't defining the `#metas` method, and Down calls [`OpenURI::Meta.init`](https://github.com/ruby/ruby/blob/df0e70b90a3198295b5640b36c57ef1266a7a258/lib/open-uri.rb#L414-L428) on the file returned by `open("...")`, which relies on `#metas` being defined.

This should be fixed in open-uri-cached, it should define the `#metas` method the same way that open-uri does, to make it a completely transparent addition.

However, a note of warning, from reading open-uri-cached's source code I noticed that its going to consume a lot of memory, because it seems to read the whole file into memory both when [writing](https://github.com/tigris/open-uri-cached/blob/4d77fd24e311e11c2daab5a06ab1a782fe5af733/lib/open-uri/cached.rb#L95) and [reading](https://github.com/tigris/open-uri-cached/blob/4d77fd24e311e11c2daab5a06ab1a782fe5af733/lib/open-uri/cached.rb#L41) from cache. You should probably raise another issue on open-uri-cached to raise awareness about this, as it is completely unnecessary to read the whole file into memory.

**Closed by janko-m** 2016-08-07 14:56 UTC

**Comment by kntmrkm** [comment] 2016-08-07 15:09
Thanks for your polite answer.

It is very useful my understand.

thanks again.
